<a href="https://colab.research.google.com/github/Saransh11-stack/Income_pred/blob/main/Income_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Libraries and Dataset**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.ensemble import RandomForestClassifier as rf
from sklearn.linear_model import LogisticRegression as lr
from sklearn.tree import DecisionTreeClassifier as dt
from sklearn.naive_bayes import GaussianNB as gnb
from sklearn.preprocessing import LabelEncoder as lb
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving train.csv to train.csv


# **DATASET**

In [ ]:
df=pd.read_csv("train.csv")

## Renaming Columns

In [ ]:
df.columns=['Age','Workclass', 'Fnlwgt', 'Education' ,'education_num' ,'marital_status' ,'occupation' ,'relationship' ,'race' ,'sex' ,'capital_gain', 'capital_loss', 'hours_per_week' ,'native_country' ,'income']
df

Age  Workclass  Fnlwgt     Education  education_num  \
0       67    Private  366425     Doctorate             16   
1       17    Private  244602          12th              8   
2       31    Private  174201     Bachelors             13   
3       58  State-gov  110199       7th-8th              4   
4       25  State-gov  149248  Some-college             10   
...    ...        ...     ...           ...            ...   
43952   52    Private   68982     Bachelors             13   
43953   19    Private  116562       HS-grad              9   
43954   30    Private  197947  Some-college             10   
43955   46    Private   97883     Bachelors             13   
43956   30    Private  375827       HS-grad              9   

           marital_status         occupation    relationship   race     sex  \
0                Divorced    Exec-managerial   Not-in-family  White    Male   
1           Never-married      Other-service       Own-child  White    Male   
2      Married-civ-spouse    Exec-managerial         Husband  White    Male   
3      Married-civ-spouse   Transport-moving         Husband  White    Male   
4           Never-married      Other-service   Not-in-family  Black    Male   
...                   ...                ...             ...    ...     ...   
43952  Married-civ-spouse    Exec-managerial         Husband  White    Male   
43953       Never-married      Other-service       Own-child  White  Female   
43954            Divorced              Sales   Not-in-family  White    Male   
43955       Never-married              Sales   Not-in-family  White  Female   
43956       Never-married  Handlers-cleaners  Other-relative  White    Male   

       capital_gain  capital_loss  hours_per_week native_country  income  
0             99999             0              60  United-States       1  
1                 0             0              15  United-States       0  
2                 0             0              40  United-States       1  
3                 0             0              40  United-States       0  
4                 0             0              40  United-States       0  
...             ...           ...             ...            ...     ...  
43952             0             0              50  United-States       1  
43953             0             0              40  United-States       0  
43954             0             0              58  United-States       0  
43955             0             0              35  United-States       0  
43956             0             0              40  United-States       0  

[43957 rows x 15 columns]

In [ ]:
df.isnull().sum()

Age                  0
Workclass         2498
Fnlwgt               0
Education            0
education_num        0
marital_status       0
occupation        2506
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     763
income               0
dtype: int64

## Data Cleaning

In [ ]:
df= df[df.Workclass != ' ?']
df= df[df.occupation != ' ?']
df= df[df.native_country != ' ?']

df

Age  Workclass  Fnlwgt     Education  education_num  \
0       67    Private  366425     Doctorate             16   
1       17    Private  244602          12th              8   
2       31    Private  174201     Bachelors             13   
3       58  State-gov  110199       7th-8th              4   
4       25  State-gov  149248  Some-college             10   
...    ...        ...     ...           ...            ...   
43952   52    Private   68982     Bachelors             13   
43953   19    Private  116562       HS-grad              9   
43954   30    Private  197947  Some-college             10   
43955   46    Private   97883     Bachelors             13   
43956   30    Private  375827       HS-grad              9   

           marital_status         occupation    relationship   race     sex  \
0                Divorced    Exec-managerial   Not-in-family  White    Male   
1           Never-married      Other-service       Own-child  White    Male   
2      Married-civ-spouse    Exec-managerial         Husband  White    Male   
3      Married-civ-spouse   Transport-moving         Husband  White    Male   
4           Never-married      Other-service   Not-in-family  Black    Male   
...                   ...                ...             ...    ...     ...   
43952  Married-civ-spouse    Exec-managerial         Husband  White    Male   
43953       Never-married      Other-service       Own-child  White  Female   
43954            Divorced              Sales   Not-in-family  White    Male   
43955       Never-married              Sales   Not-in-family  White  Female   
43956       Never-married  Handlers-cleaners  Other-relative  White    Male   

       capital_gain  capital_loss  hours_per_week native_country  income  
0             99999             0              60  United-States       1  
1                 0             0              15  United-States       0  
2                 0             0              40  United-States       1  
3                 0             0              40  United-States       0  
4                 0             0              40  United-States       0  
...             ...           ...             ...            ...     ...  
43952             0             0              50  United-States       1  
43953             0             0              40  United-States       0  
43954             0             0              58  United-States       0  
43955             0             0              35  United-States       0  
43956             0             0              40  United-States       0  

[43957 rows x 15 columns]

## Data Preprocessing

In [ ]:
le= lb()

le.fit(df['Workclass'])
lst= le.transform(df['Workclass'])
df['Workclass']= df['Workclass'].replace(to_replace= list(le.classes_), value= list(set(lst)))

#df['Workclass']=le.fit_transform(df['Workclass'])
le.fit(df['Education'])
lst=le.transform(df['Education'])
df['Education']= df['Education'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['marital_status'])
lst=le.transform(df['marital_status'])
df['marital_status']= df['marital_status'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['occupation'])
lst=le.transform(df['occupation'])
df['occupation']= df['occupation'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['relationship'])
lst=le.transform(df['relationship'])
df['relationship']= df['relationship'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['race'])
lst=le.transform(df['race']) #encoding done and stored in same columns
df['race']= df['race'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['sex'])
lst=le.transform(df['sex'])
df['sex']= df['sex'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['native_country'])
lst=le.transform(df['native_country'])
df['native_country']= df['native_country'].replace(to_replace= list(le.classes_), value= list(set(lst)))

le.fit(df['income'])
lst=le.transform(df['income'])
df['income']= df['income'].replace(to_replace= list(le.classes_), value= list(set(lst)))

In [ ]:
df

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0       50          4   83311          9             13               2   
1       38          2  215646         11              9               0   
2       53          2  234721          1              7               2   
3       28          2  338409          9             13               2   
4       37          2  284582         12             14               2   
...    ...        ...     ...        ...            ...             ...   
32555   27          2  257302          7             12               2   
32556   40          2  154374         11              9               2   
32557   58          2  151910         11              9               6   
32558   22          2  201490         11              9               4   
32559   52          3  287927         11              9               2   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0               3             0     4    1             0             0   
1               5             1     4    1             0             0   
2               5             0     2    1             0             0   
3               9             5     2    0             0             0   
4               3             5     4    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32555          12             5     4    0             0             0   
32556           6             0     4    1             0             0   
32557           0             4     4    0             0             0   
32558           0             3     4    1             0             0   
32559           3             5     4    0         15024             0   

       hours_per_week  native_country  income  
0                  13              38       0  
1                  40              38       0  
2                  40              38       0  
3                  40               4       0  
4                  40              38       0  
...               ...             ...     ...  
32555              38              38       0  
32556              40              38       1  
32557              40              38       0  
32558              20              38       0  
32559              40              38       1  

[30161 rows x 15 columns]

## Dataset Creation

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
print(x.shape)
print(y.shape)

(43957, 14)
(43957,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size= 0.3)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(30769, 14)
(30769,)
(13188, 14)
(13188,)


**Applying** **Standardization**

In [ ]:
scaler= MinMaxScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

# **MODELS**

## A generic functoin for all models

In [ ]:
from sklearn.metrics import confusion_matrix as cm,classification_report as cr

def apply_models(m,x_train,x_test,y_train,y_test):
  m.fit(x_train,y_train)
  print('Training Score\n',m.score(x_train,y_train))
  print('\nTesting Score\n',m.score(x_test,y_test))
  y_pred=m.predict(x_test)
  print("\ny_pred\n",y_pred)
  print("\nConfusion Matrix\n",cm(y_test,y_pred))
  print("\nClassification Report\n",cr(y_test,y_pred))

## Decision Tree

In [ ]:
m_dt= dt(criterion= 'entropy', min_samples_split= 400)
apply_models(m_dt,x_train,x_test,y_train,y_test)

Training Score
 0.8636614774610809

Testing Score
 0.8622232332423415

y_pred
 [0 0 0 ... 0 0 1]

Confusion Matrix
 [[9518  571]
 [1246 1853]]

Classification Report
               precision    recall  f1-score   support

           0       0.88      0.94      0.91     10089
           1       0.76      0.60      0.67      3099

    accuracy                           0.86     13188
   macro avg       0.82      0.77      0.79     13188
weighted avg       0.86      0.86      0.86     13188



## Random Forest Classifier

In [ ]:
m_rf= rf(criterion= 'entropy', min_samples_split= 20, max_depth= 20)
apply_models(m_rf,x_train,x_test,y_train,y_test)

Training Score
 0.8996392472943547

Testing Score
 0.8701091901728845

y_pred
 [0 0 0 ... 0 0 1]

Confusion Matrix
 [[9566  523]
 [1190 1909]]

Classification Report
               precision    recall  f1-score   support

           0       0.89      0.95      0.92     10089
           1       0.78      0.62      0.69      3099

    accuracy                           0.87     13188
   macro avg       0.84      0.78      0.80     13188
weighted avg       0.86      0.87      0.86     13188



## Logistic Regression

In [ ]:
m_lr= lr()
apply_models(m_lr,x_train,x_test,y_train,y_test)

Training Score
 0.8250186876401573

Testing Score
 0.8218835304822566

y_pred
 [0 0 0 ... 0 0 1]

Confusion Matrix
 [[9463  626]
 [1723 1376]]

Classification Report
               precision    recall  f1-score   support

           0       0.85      0.94      0.89     10089
           1       0.69      0.44      0.54      3099

    accuracy                           0.82     13188
   macro avg       0.77      0.69      0.71     13188
weighted avg       0.81      0.82      0.81     13188



## KNN

In [ ]:
m_knn= knn(n_neighbors= 21)
apply_models(m_knn,x_train,x_test,y_train,y_test)

Training Score
 0.845298839741298

Testing Score
 0.8415225962996664

y_pred
 [0 0 0 ... 1 0 1]

Confusion Matrix
 [[9285  804]
 [1286 1813]]

Classification Report
               precision    recall  f1-score   support

           0       0.88      0.92      0.90     10089
           1       0.69      0.59      0.63      3099

    accuracy                           0.84     13188
   macro avg       0.79      0.75      0.77     13188
weighted avg       0.83      0.84      0.84     13188



## Gaussian Naive Bayes

In [ ]:
m_gnb= gnb()
apply_models(m_gnb,x_train,x_test,y_train,y_test)

Training Score
 0.8044460333452501

Testing Score
 0.8050500454959054

y_pred
 [0 0 0 ... 0 0 1]

Confusion Matrix
 [[9582  507]
 [2064 1035]]

Classification Report
               precision    recall  f1-score   support

           0       0.82      0.95      0.88     10089
           1       0.67      0.33      0.45      3099

    accuracy                           0.81     13188
   macro avg       0.75      0.64      0.66     13188
weighted avg       0.79      0.81      0.78     13188



# **HENCE, RANDOM FOREST IS A CLEAR WINNER AMONGST ALL FIVE**